### ISSUE TITLE
Add Song Names for Dynamic Music's tracks

### ISSUE THREAD

**Issue by Just-Leah** [Scotsguy/now-playing#9]
I have this mod with the mod [Dynamic Music](https://www.curseforge.com/minecraft/mc-mods/dynamic-music) and the toasts from this mod do not always appear with the other mod.
**Expected behavior**
The toasts appear for the tracks played.
**Actual result**
The toasts do not appear for some songs.

For extra context, I also have [Music Duration Reducer](https://www.curseforge.com/minecraft/mc-mods/music-duration-reducer) installed, but the issue happened before I added it

**Comment by Just-Leah** [comment]
For extra context, I’m on fabric
Sorry for not clarifying that earlier, I forgot that MDR is for forge as well

**Comment by Scotsguy** [comment]
Sorry for taking ages to get to this;
Dynamic Music adds new songs. These have new names, so to avoid being unhelpful if now playing doesn't know what to call it it'll just not show any toast at all. Maybe I'll add them, but since I only update for the newest version of Minecraft, currently 1.18.2, and Dynamic Music seemingly does not work on that version, it'll have to wait a bit.

**Comment by Scotsguy** [comment]
Closing, since Dynamic Music still hasn't been updated. I'll take another look when that gets an update.
